# ======================== Elasticsearch Configuration =========================
cluster.name: es-cluster
node.name: master 
node.master: true
node.data: false
node.attr.rack: r1 
bootstrap.memory_lock: true 
http.port: 9200
network.host: 0.0.0.0
transport.tcp.port: 9300
discovery.seed_hosts: ["10.10.10.106:9301","10.10.10.106:9302","10.10.10.106:9303","10.10.10.106:9304"] 
cluster.initial_master_nodes: ["master"] 
gateway.recover_after_nodes: 2
http.cors.enabled: true
http.cors.allow-origin: "*"
