version: '3.1'
services:
  mongodb4:
    image: mongo:4.0
    restart: always
    container_name: mongo4
    volumes:
      - ./data/db/mongo4:/data/db
      - ./keyFile/mongodb.key:/data/mongodb.key
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongoNet
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@

networks:
  mongoNet:
    driver: bridge
