version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-5.0-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /data/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - /data/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /data/zabbix/export:/var/lib/zabbix/export:rw
   - /data/zabbix/modules:/var/lib/zabbix/modules:ro
   - /data/zabbix/enc:/var/lib/zabbix/enc:ro
   - /data/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /data/zabbix/mibs:/var/lib/zabbix/mibs:ro
  links:
   - mysql-server:mysql-server
   - zabbix-java-gateway:zabbix-java-gateway
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  env_file:
   - .env_db_mysql
   - .env_srv
  depends_on:
   - mysql-server
   - zabbix-java-gateway
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
  ports:
   - "80:8080"
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /data/zabbix/etc/ssl/nginx:/etc/ssl/nginx:ro
   - /data/zabbix/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
   - ./simkai.ttf:/usr/share/zabbix/fonts/graphfont.ttf:ro
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
  env_file:
   - .env_db_mysql
   - .env_web
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-5.0-latest
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /data/zabbix/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - /data/zabbix/modules:/var/lib/zabbix/modules:ro
   - /data/zabbix/enc:/var/lib/zabbix/enc:ro
   - /data/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_agent
  privileged: true
  pid: "host"

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:alpine-5.0-latest
  ports:
   - "10052:10052"
  volumes:
   - /etc/localtime:/etc/localtime:ro
  env_file:
   - .env_java

 mysql-server:
  image: mysql:8.0
  command: [mysqld,--character-set-server=utf8,--collation-server=utf8_bin,--default-authentication-plugin=mysql_native_password]
  #command:
  # - mysqld
  # - --character-set-server=utf8
  # - --collation-server=utf8_bin
  # - --default-authentication-plugin=mysql_native_password
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /data/zabbix/mysql:/var/lib/mysql:rw
  ports:
   - "3306:3306"
  env_file:
   - .env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  stop_grace_period: 1m

secrets:
  MYSQL_USER:
    file: ./.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD
