version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.12.0
    network_mode: host
    hostname: prometheus
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/prometheus/rules/rules.yml:/etc/prometheus/rules/rules.yml
      - /data/prometheus/data:/prometheus
      - /data/prometheus/discovery:/etc/prometheus/discovery
    command:
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  alertmanager:
    image: prom/alertmanager:v0.18.0
    network_mode: host
    hostname: alertmanager
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /data/alertmanager/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /data/alertmanager/data:/alertmanager
    ports:
      - '9093:9093'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  cadvisor:
    image: google/cadvisor:v0.33.0
    network_mode: host
    hostname: cadvisor
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - '8080:8080'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  node-exporter:
    image: prom/node-exporter:v0.18.1
    network_mode: host
    hostname: node-exporter
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs 
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    command: 
      - --path.rootfs=/host
      - --collector.systemd
      - --collector.mountstats
      - --collector.processes
      - --collector.interrupts
      - --collector.textfile.directory=/usr
      - --collector.filesystem.ignored-fs-types=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
      - --collector.diskstats.ignored-devices=^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\\d+n\\d+p)\\d+$$
      - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($$|/)
      - --collector.systemd.unit-whitelist=^ceph.*$$
    ports:
      - '9100:9100'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  pushgateway:
    image: prom/pushgateway:v1.0.0
    network_mode: host
    hostname: node-pushgateway
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - '9091:9091'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  grafana:
    image: grafana/grafana:6.3.5
    network_mode: host
    hostname: grafana
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - '/data/grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - '/data/grafana/data:/var/lib/grafana'
    ports:
      - '3000:3000'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

volumes:
  grafana_data: {}
  prometheus_data: {}

