version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.12.0
    network_mode: host
    hostname: prometheus
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/prometheus/rules/rules.yml:/etc/prometheus/rules/rules.yml
      - /data/prometheus/data:/prometheus
      - /data/prometheus/discovery:/etc/prometheus/discovery
    command:
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  alertmanager:
    image: prom/alertmanager:v0.18.0
    network_mode: host
    hostname: alertmanager
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /data/alertmanager/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /data/alertmanager/data:/alertmanager
    ports:
      - '9093:9093'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m
        
  grafana:
    image: grafana/grafana:6.3.5
    network_mode: host
    hostname: grafana
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - '/data/grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - '/data/grafana/data:/var/lib/grafana'
    ports:
      - '3000:3000'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

volumes:
  grafana_data: {}
  prometheus_data: {}
